#!/bin/bash

echo "Creating new MANIFEST with default Build files"
echo Build.PL > MANIFEST.new
echo "Makefile.PL" >>MANIFEST.new
echo "Changes" >>MANIFEST.new
echo "MANIFEST" >>MANIFEST.new
echo "META.yml # Will be created by 'make dist'" >>MANIFEST.new
echo "README" >>MANIFEST.new
echo "config.xml" >>MANIFEST.new
echo "servers.xml" >>MANIFEST.new
echo "packdir2xml" >>MANIFEST.new

echo "Adding test files from t/ directory"
ls -1 t/*.t >> MANIFEST.new

echo "Adding libraries from lib/ directory"
ls -1 lib/*.pm lib/*/*.pm lib/*/*/*.pm lib/*/*/*/*.pm >> MANIFEST.new
