# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         slackget10
version:      0.08
version_from: lib/slackget10.pm
installdirs:  site
requires:
    Data::Dumper:                  2.121_02
    File::Copy:                    2.08
    HTTP::Status:                  1.28
    LWP::Simple:                   1.41
    Net::FTP:                      2.75
    Qt:                            3.008
    Test::More:                    0.47
    Time::HiRes:                   1.66
    XML::Simple:                   2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
