--- #YAML:1.0
name: slackget10
version: 0.01
author:
  - DUPUIS Arnaud <a.dupuis@infinityperl.org>
abstract: The great new slackget10!
license: gpl
generated_by: Module::Build version 0.2609, without YAML.pm
